<ips:template parameters="$log, $event, $rule, $conditions, $actions, $subrules" />

<div class='ipsPad'>

	<div class='ipsMessage ipsMessage_info' style='margin-right:30px; padding-right:20px;'>Event: <strong>{$event->title()}</strong> <span style='float:right'>{expression="\IPS\DateTime::ts( $log[ 'time' ] )"}</span></div>
	
	<h2 style="font-weight:normal; padding:0 15px;">Rule Overview</h2>
	<ul>
		<li>Name: <strong>{{if $rule}}{$rule->title}{{else}}Unknown (deleted){{endif}}</strong></li>
		<li>Status: <strong>{$log[ 'message' ]}</strong></li>
		<li>Result: <strong>{$log[ 'result' ]}</strong></li>
	</ul>
	
	<h3 style="margin:25px 15px 0;"><i class="fa fa-filter"></i> Conditions</h3>
	{$conditions|raw}
	
	<h3 style="margin:25px 15px 0;"><i class="fa fa-flash"></i> Actions</h3>
	{$actions|raw}
	
	<h3 style="margin:25px 15px 0;"><i class="fa fa-gavel"></i> Linked Rules</h3>
	{$subrules|raw}
	
</div>